### ISSUE TITLE
redo authors 

### ISSUE THREAD

**Issue by tnh** [cevoaustralia/cevoaustralia.github.io#114]
I think what we'll need to do is refactor `posts.html` to support multiple blog authors.

**Comment by tnh** [comment]
https://github.com/cevoaustralia/cevoaustralia.github.io/blob/1c3682fa676f49397e19c18bfbb0d759b83466a6/_layouts/post.html#L15

**Comment by mngau** [comment]
Doesn't it support multiple authors currently?

**Comment by tnh** [comment]
Reckon we'll need to change our blog posts to be something like:

https://gist.github.com/ravasthi/1834570

**Comment by mngau** [comment]
Ah I see what you mean, that does look better.

**Comment by tnh** [comment]
https://github.com/cevoaustralia/cevoaustralia.github.io/blame/develop/_posts/2015-05-03-The-Consul-of-Elders.markdown#L11
eg
```
authors:
  trent:
    name: Trent Hornibrook
    display_name: Trent
    gravatar: 1111111
    email: trent.hornibrook@cevo.com.au
    twitter: mysqldbahelp
    github: tnhtnh
```

and within `post.html` support that - like https://gist.github.com/ravasthi/1834570
